import Image from "next/image";
import Link from "next/link";
import {SiteHeader,SiteFooter} from "./components/site-chrome";
import {Icon} from "./components/icons";
import {OperationsConsole} from "./components/operations-console";
import {IcemanVisual,StorageVisual,ObservabilityVisual} from "./components/project-visuals";
import {skillGroups} from "./data/skills";
const github="https://github.com/Semicrypt";
const linkedin="https://www.linkedin.com/in/nwachukwu-ifeanyi-divine-31b9793a6";
const email="https://mail.google.com/mail/?view=cm&fs=1&to=nifeanyidivine@gmail.com&su=Portfolio%20Enquiry";
function Tags({items}:{items:string[]}){return <div className="tags">{items.map(item=><span className="tag" key={item}>{item}</span>)}</div>}
function SectionHeading({number,label,title,description}:{number:string;label:string;title:string;description?:string}){return <div className="section-heading"><div><p className="eyebrow"><span>{number}</span> {label}</p><h2>{title}</h2></div>{description&&<p className="section-description">{description}</p>}</div>}
export default function Home(){return <><SiteHeader/><main id="main-content">
<section id="home" className="hero"><div className="hero-grid" aria-hidden="true"/><div className="container hero-inner"><div className="hero-copy"><div className="hero-intro"><Image src="/divine-profile.png" alt="Portrait of Nwachukwu Ifeanyi Divine" width={56} height={56} preload className="hero-portrait"/><div><p>Nwachukwu Ifeanyi Divine</p><span>Cloud & DevOps Engineer · Lagos, NG</span></div></div><p className="hero-kicker"><span className="status-dot"/> BUILDING ACROSS CLOUDS</p><h1>I build the systems<br/>behind <span>what’s next.</span></h1><p className="hero-description">From the first container to cloud delivery. I build tools, automate infrastructure, and make complex systems easier to run.</p><div className="hero-actions"><a className="button button-primary" href="#projects">Explore my work <Icon name="arrow"/></a><a className="button button-secondary" href="/resume.pdf" download="Nwachukwu-Ifeanyi-Divine-Resume.pdf">Download résumé <Icon name="download"/></a></div><div className="hero-socials"><a href={github} target="_blank" rel="noreferrer">GitHub ↗</a><a href={linkedin} target="_blank" rel="noreferrer">LinkedIn ↗</a><span className="hero-location"><Icon name="globe"/> Lagos, Nigeria</span></div></div><OperationsConsole/></div><div className="container hero-bottom"><span>CODE. CLOUD. CONTINUOUS IMPROVEMENT.</span><a href="#projects">SCROLL TO EXPLORE <span aria-hidden="true">↓</span></a></div></section>
<div className="stack-ribbon"><div className="container"><span>THE TOOLKIT</span><div>{["AWS","Microsoft Azure","Docker","Kubernetes","Terraform","GitHub Actions","Grafana","Linux"].map(s=><span key={s}>{s}</span>)}</div></div></div>
<section id="projects" className="section container"><SectionHeading number="01" label="SELECTED WORK" title="Built to solve. Designed to operate." description="A closer look at the tools, cloud applications, and infrastructure I’m building—and the decisions behind them."/>
<article className="featured-project"><div className="featured-copy"><div className="project-meta"><span>01 / DEVELOPER TOOLING</span><span className="project-status"><i/> In development</span></div><div className="project-wordmark"><span className="project-symbol"><Icon name="terminal"/></span><h3>Iceman</h3></div><h4>DevOps, with the<br/>operator in control.</h4><p>A natural-language DevOps CLI that connects project inspection and diagnostics with command previews, approval gates, and live operational evidence.</p><Tags items={["Python","Docker","Linux","DevOps automation"]}/><Link className="text-link" href="/projects/iceman">Inside the build <Icon name="arrow"/></Link></div><div className="featured-art"><div className="project-orbit" aria-hidden="true"/><IcemanVisual/><div className="art-footnote"><Icon name="shield"/> Context before commands. Evidence after execution.</div></div></article>
<div className="project-grid"><article className="project-card"><StorageVisual/><div className="project-card-body"><div className="project-meta"><span>02 / AWS FILE STORAGE</span><Icon name="cloud"/></div><h3>CloudDrop<span className="project-period">.</span></h3><p>Connecting the file experience to the cloud architecture behind it. AWS-focused storage and delivery, built as one complete application workflow.</p><Tags items={["AWS","File storage","Cloud architecture"]}/><Link className="text-link" href="/projects/clouddrop">Explore the architecture <Icon name="arrow"/></Link></div></article><article className="project-card"><StorageVisual azure/><div className="project-card-body"><div className="project-meta"><span>03 / AZURE FILE PLATFORM</span><Icon name="cloud"/></div><h3>AzureDrop<span className="project-period">.</span></h3><p>Authenticated uploads, downloads, and share links. Azure Blob Storage connected to a Node.js/Express backend and PostgreSQL.</p><Tags items={["Azure Blob Storage","Express","PostgreSQL"]}/><Link className="text-link" href="/projects/azuredrop">Explore the architecture <Icon name="arrow"/></Link></div></article></div>
<article className="minerva-project"><div className="minerva-copy"><div className="project-meta"><span>04 / OBSERVABILITY & OPERATIONS</span></div><h3>Minerva Sentinel<span className="project-period">.</span></h3><p>From infrastructure signals to incident response. A hybrid-cloud monitoring platform that brings hosts, containers, metrics, and operational events into one view.</p><Tags items={["AWS / EKS","Docker","GitHub Actions","PostgreSQL"]}/><Link className="text-link" href="/projects/minerva-sentinel">Read the engineering story <Icon name="arrow"/></Link></div><ObservabilityVisual/></article>
<div className="lab-heading"><span className="eyebrow">ALSO IN THE WORKSHOP</span><p>The infrastructure behind the applications.</p></div><div className="lab-grid"><a className="lab-card" href="https://github.com/Semicrypt/nodejs-docker-app" target="_blank" rel="noreferrer"><Icon name="box"/><h3>Containerized Node.js</h3><p>Docker images, Compose workflows, and repeatable application environments.</p><span>View repository ↗</span></a><Link className="lab-card" href="/projects/minerva-sentinel#architecture"><Icon name="layers"/><h3>Kubernetes & EKS</h3><p>Workload deployments, service networking, and database connectivity in the Minerva build.</p><span>Explore the deployment →</span></Link><a className="lab-card" href="#skills"><Icon name="code"/><h3>Terraform & automation</h3><p>Infrastructure as code, cloud networking, and environment configuration practice.</p><span>View engineering stack ↓</span></a></div>
</section>
<section id="skills" className="section skills-section"><div className="container"><SectionHeading number="02" label="ENGINEERING STACK" title="Tools with a purpose." description="Across application code, infrastructure, and operations. The stack changes; the focus on clear, repeatable systems stays."/><div className="skills-list">{skillGroups.map((group,i)=><article key={group.title} className="skill-row"><span className="skill-index">0{i+1}</span><div><h3>{group.title}</h3><p>{group.description}</p></div><Tags items={group.items}/></article>)}</div></div></section>
<section id="about" className="section container about-section"><div className="about-portrait"><Image src="/divine-profile.png" alt="Nwachukwu Ifeanyi Divine" width={727} height={728} sizes="(max-width: 700px) 80vw, 360px"/><div className="portrait-caption"><span>N. IFEANYI DIVINE</span><span>LAGOS, NG ↗</span></div></div><div className="about-copy"><p className="eyebrow"><span>03</span> THE ENGINEER BEHIND THE BUILDS</p><h2>Curious by nature.<br/><span>Hands-on by default.</span></h2><p>I’m a Cloud and DevOps Engineer with a Computer Science background. I like understanding the whole system: the application, the infrastructure it runs on, and what happens when something breaks.</p><p>My work brings AWS, Azure, containers, automation, and observability together through practical projects. I care about systems that are repeatable, understandable, and easier for the next engineer to operate.</p><div className="about-principles"><span><Icon name="code"/> Build with context</span><span><Icon name="activity"/> Make it observable</span><span><Icon name="shield"/> Keep control visible</span></div><a className="text-link" href="/resume.pdf" download="Nwachukwu-Ifeanyi-Divine-Resume.pdf">The full résumé <Icon name="download"/></a></div></section>
<section id="experience" className="section experience-section"><div className="container experience-layout"><div><p className="eyebrow"><span>04</span> EXPERIENCE & FOUNDATION</p><h2>Learning by<br/>building.</h2><p className="section-description">Practical engineering experience, a Computer Science foundation, and a workshop that keeps growing.</p></div><div className="timeline"><article><div className="timeline-top"><span className="eyebrow">INDEPENDENT ENGINEERING</span><span>Ongoing</span></div><h3>Cloud & DevOps Projects</h3><p>Building Iceman, CloudDrop, AzureDrop, and Minerva Sentinel across cloud infrastructure, containers, CI/CD, monitoring, and application delivery.</p></article><article><div className="timeline-top"><span className="eyebrow">WHINZET DIGITAL ID LIMITED</span><span>Jan — Oct 2025</span></div><h3>Junior Cloud & Network Engineer</h3><span className="timeline-type">Industrial Training Placement</span><p>Supported cloud and network engineering activities, infrastructure troubleshooting, deployment workflows, and technical operations.</p></article><div id="education" className="education"><p className="eyebrow">EDUCATION / WESLEY UNIVERSITY, ONDO</p><div><h3>B.Sc. (Hons) Computer Science</h3><span>2023 — 2026</span></div><p>Software development, databases, networks, operating systems, and systems analysis.</p><div><h3>M.Sc. Computer Science</h3><span>2027 — Expected 2028</span></div><p>Planned academic progression in Computer Science.</p></div><div id="training" className="education"><p className="eyebrow">CONTINUOUS LEARNING</p><div><h3>TechCrush · Cloud Computing & DevOps</h3><span>Jul — Sep 2026</span></div><p>Completed · Certificate received</p><div><h3>TechSphere Academy · Cloud Computing</h3><span>Oct 2026 — Jan 2027</span></div><p>Enrolled · Program begins October 2026</p></div></div></div></section>
<section id="contact" className="contact-section"><div className="contact-grid" aria-hidden="true"/><div className="container contact-inner"><p className="eyebrow"><span className="status-dot"/> LET’S BUILD SOMETHING USEFUL</p><h2>Your next challenge.<br/><span>My next deep dive.</span></h2><p>Have a cloud, infrastructure, or DevOps opportunity?<br/>Let’s talk about what we can build.</p><a className="button button-primary" href={email} target="_blank" rel="noreferrer">Start a conversation <Icon name="arrow"/></a><a className="contact-email" href={email} target="_blank" rel="noreferrer">nifeanyidivine@gmail.com ↗</a><div className="contact-links"><a href={github} target="_blank" rel="noreferrer">GitHub ↗</a><a href={linkedin} target="_blank" rel="noreferrer">LinkedIn ↗</a></div></div></section>
</main><SiteFooter/></>}
